# TERRAFORM
#  www.TerraformCorp.com
#
# Sample Documentation
# https://support.atlassian.com/bitbucket-cloud/docs/deploy-to-aws-with-elastic-beanstalk/
# 

image: atlassian/default-image:2

pipelines:
  branches:  # Pipelines that run automatically on a commit to a branch can also be triggered manually
   release/demo-nft-sportscast-net:
    - step:
        name: "Zip Only"
        script:
          - echo "Zip Only"
          - ls -la
          # - rm -rf bitbucket-pipelines.yml
          # - chmod u+x ./build-run.sh
          # - ls -la
          - cp build-run.sh build-run-it.sh
          - zip -r demo-nft-sportscast-net.zip * .[^.]*       
        
        # Define an artifact to pass the zip file to the next step
        artifacts: 
          - demo-nft-sportscast-net.zip
    - step:
        name: "Deploy to demo-nft-sportscast-net"
        # Track staging environments builds using deployments.
        deployment: staging
        script:
        - echo "Deploy to demo-nft-sportscast-net"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
          variables:
            DEBUG: 'TRUE'
            # upload-only is upload to S3 only, but dont deploy to beanstalk
            # COMMAND: 'upload-only'
            AWS_ACCESS_KEY_ID: $AWS_KEYID__demo_nft
            AWS_SECRET_ACCESS_KEY: $AWS_KEYSECRET__demo_nft
            AWS_DEFAULT_REGION: 'us-west-2'
            APPLICATION_NAME: 'NFT Storefront'
            ENVIRONMENT_NAME: 'demo-nft-sportscast-net'
            ZIP_FILE: 'demo-nft-sportscast-net.zip'
            S3_BUCKET: 'demo-nft-sportscast-net'
            VERSION_LABEL: '_$(date +%Y-%m-%d_%H:%M:%S)_${BITBUCKET_COMMIT:0:8}'
  release/nft-sportscast-net:
    - step:
        name: "Zip: nft-sportscast-net"
        script:
          - ls -la
          - zip -r nft-sportscast-net.zip * .[^.]*
        artifacts: 
          - nft-sportscast-net.zip
    - step:
        name: "Deploy: nft-sportscast-net"
        # Track staging environments builds using deployments.
        deployment: production
        script:
        - echo "Deploy: nft-sportscast-net"
        - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
          variables:
            DEBUG: 'TRUE'
            AWS_ACCESS_KEY_ID: $AWS_KEYID__demo_nft
            AWS_SECRET_ACCESS_KEY: $AWS_KEYSECRET__demo_nft
            AWS_DEFAULT_REGION: 'us-west-2'
            APPLICATION_NAME: 'NFT Storefront'
            ENVIRONMENT_NAME: 'nft-sportscast-net'
            ZIP_FILE: 'nft-sportscast-net.zip'
            S3_BUCKET: 'nft-sportscast-net'
            VERSION_LABEL: '_$(date +%Y-%m-%d_%H:%M:%S)_${BITBUCKET_COMMIT:0:8}'